pipeline {
    agent any

    stages {

        stage('Restore') {
            steps {
                sh 'dotnet restore'
            }
        }

        stage('Build') {
            steps {
                sh 'dotnet build --no-restore'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t hotel-booking-api .'
            }
        }

    }
}